[package]
name = "grappolo"
version = "0.1.0"
authors = ["Ricardo Rocha <ricardo@xrrocha.net>"]
edition = "2018"

[lib]
name="grappolo"
path = "src/lib.rs"
test = true

[[bin]]
name = "grappolo"
path = "src/main.rs"

[dependencies]
strsim = "0.9.2"
itertools = "0.8.0"
rayon = "1.0.3"
